# Generated by Django 4.0.4 on 2022-05-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cource_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
