# Generated by Django 4.0.4 on 2022-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_timetable_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('Amaliy', 'Amaliy'), ("Ma'ruza", "Ma'ruza"), ('Seminar', 'Seminar'), ('Laboratoriya', 'Laboratoriya')], max_length=20, null=True),
        ),
    ]
