# Generated by Django 4.0.4 on 2022-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='chorshanba',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='dushanba',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='juma',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='payshanba',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='seshanba',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='shanba',
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_day',
            field=models.CharField(choices=[('dushanba', 'dushanba'), ('seshanba', 'seshanba'), ('chorshanba', 'chorshanba'), ('payshanba', 'payshanba'), ('juma', 'juma'), ('shanba', 'shanba')], default='dushanba', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson',
            field=models.ManyToManyField(null=True, to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
