# Generated by Django 4.0.4 on 2022-05-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_timetable_chorshanba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.courses'),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
