# Generated by Django 4.0.4 on 2022-05-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
    ]
